{
  "env": { "es6": true, "browser": true, "commonjs": true },
  "extends": "airbnb",
  "rules":
    {
      "arrow-body-style": 0,
      "import/prefer-default-export": "off",
      "max-len": ["error", { "code": 280 }],
    },
}
